config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :phones
  resources :addresses
  resources :contacts
  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates_presence_of :name, :age, :email

	has_one :address, :dependent => :destroy
	has_one :account, :dependent => :destroy
	has_one :phone, :dependent => :destroy

	accepts_nested_attributes_for :address, :account, :phone

	def self.search(search)
		if search
			where('name LIKE ?', "%#{search}%")
		else
			all
		end
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    if params[:search]
      @contacts = Contact.search(params[:search])
    else
      @contacts = Contact.all
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_address
    @contact.build_phone
    @contact.build_account
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(
                                      :name,
                                      :age,
                                      :email,
                                      {address_attributes: [:street, :cep, :city, :state]},
                                      {phone_attributes: [:phone]},
                                      {account_attributes: [:username, :password]},
                                      :search)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: 'label' %>
    <%= form.text_field :name, id: :contact_name %>
  </div>

  <div class="field">
    <%= form.label :age, class: 'label' %>
    <%= form.text_field :age, id: :contact_age %>
  </div>

  <div class="field">
    <%= form.label :email, class: 'label' %>
    <%= form.text_field :email, id: :contact_email %>
  </div>

  <%= form.fields_for :address do |address_field| %>
    <div class="field">
      <%= form.label :street, class: 'label' %>
      <%= address_field.text_field :street, class: 'input' %>
    </div>
    <div class="field">
      <%= form.label :cep, class: 'label' %>
      <%= address_field.text_field :cep, class: 'input' %>
    </div>
    <div class="field">
      <%= form.label :city, class: 'label' %>
      <%= address_field.text_field :city, class: 'input' %>
    </div>
    <div class="field">
      <%= form.label :state, class: 'label' %>
      <%= address_field.text_field :state, class: 'input' %>
    </div>
  <% end %>

  <%= form.fields_for :phone do |phone_field| %>
    <div class="field">
      <%= form.label :phone, class: 'field' %>
      <%= phone_field.text_field :phone, class: 'input' %>
    </div>
  <% end %>

  <%= form.fields_for :account do |account_field| %>
    <div class="field">
      <%= form.label :username, class: 'field' %>
      <%= account_field.text_field :username, class: 'input' %>
    </div>
    <div class="field">
      <%= form.label :password, class: 'field' %>
      <%= account_field.text_field :password, class: 'input', type: 'password' %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit 'Create', class: 'button-is-success' %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<%= content_for :body do %>

	<h1>Editing Contact</h1>

	<%= render 'form', contact: @contact %>

	<%= link_to 'Show', @contact, class: 'button' %> |
	<%= link_to 'Back', contacts_path, class: 'button' %>

<% end %>

app/views/contacts/index.html.erb
<%= content_for :body do %>

<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<%= form_tag(contacts_path(@contacts), method: :get) do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search contact" %>
  <%= submit_tag "Search", name: nil %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.age %></td>
        <td><%= contact.email %></td>
        <td><%= link_to 'Show', contact, class: 'button' %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact), class: 'button' %></td>
        <td><%= link_to 'Destroy', contact, class: 'button', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path, class: 'button' %>
<%= link_to 'Back to menu', home_index_path, class: 'button' %>

<% end %>

app/views/contacts/new.html.erb
<%= content_for :body do %>

	<h1>New Contact</h1>

	<%= render 'form', contact: @contact %>

	<%= link_to 'Back', contacts_path, class: 'button' %>

<% end %>

app/views/contacts/show.html.erb
<%= content_for :body do %>

	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Name:</strong>
	  <%= @contact.name %>
	</p>

	<p>
	  <strong>Age:</strong>
	  <%= @contact.age %>
	</p>

	<p>
	  <strong>Email:</strong>
	  <%= @contact.email %>
	</p>

	<%= link_to 'Edit', edit_contact_path(@contact), class: 'button' %> |
	<%= link_to 'Back', contacts_path, class: 'button' %>

<% end %>