config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :phones
  resources :addresses
  resources :contacts
  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :contact

  validates_presence_of :contact
  validates_presence_of :username, :password
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:username, :password, :contact_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :account_username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :account_password %>
  </div>

  <div class="field">
    <%= form.label :contact_id, class: 'field' %>
    <%= collection_select(
                        :account,
                        :contact_id,
                        Contact.all,
                        :id,
                        :name,
                        {},
                        html_options={}
                        ) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<%= content_for :body do %>

	<h1>Editing Account</h1>
	<%= render 'form', account: @account %>

	<%= link_to 'Show', @account, class: 'button' %> |
	<%= link_to 'Back', accounts_path, class: 'button' %>

<% end %>

app/views/accounts/index.html.erb
<%= content_for :body do %>

  <p id="notice"><%= notice %></p>

  <h1>Accounts</h1>

  <table>
    <thead>
      <tr>
        <th>Username</th>
        <th>Password</th>
        <th>Contact</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @accounts.each do |account| %>
        <tr>
          <td><%= account.username %></td>
          <td><%= account.password %></td>
          <td><%= account.contact.name %></td>
          <td><%= link_to 'Show', account, class: 'button' %></td>
          <td><%= link_to 'Edit', edit_account_path(account), class: 'button' %></td>
          <td><%= link_to 'Destroy', account, class: 'button', method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Account', new_account_path, class: 'button' %>
  <%= link_to 'Back to menu', home_index_path, class: 'button' %>

<% end %>

app/views/accounts/new.html.erb
<%= content_for :body do %>
	<h1>New Account</h1>

	<%= render 'form', account: @account %>

	<%= link_to 'Back', accounts_path, class: 'button' %>

<% end %>

app/views/accounts/show.html.erb
<%= content_for :body do %>
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Username:</strong>
	  <%= @account.username %>
	</p>

	<p>
	  <strong>Password:</strong>
	  <%= @account.password %>
	</p>

	<p>
	  <strong>Contact:</strong>
	  <%= @account.contact.name %>
	</p>

	<%= link_to 'Edit', edit_account_path(@account), class: 'button' %> |
	<%= link_to 'Back', accounts_path, class: 'button' %>

<% end %>